# GitHub Secrets Configuration
# This file documents required secrets for the workflows
# DO NOT store actual secret values here!

repository_secrets:
  # Lark Integration
  lark:
    LARK_BOT_URL:
      description: URL of the Lark bot server (e.g., https://your-bot.vercel.app)
      required: true
      example: https://lark-bot.vercel.app
    
    LARK_WEBHOOK_URL:
      description: Lark webhook URL for simple notifications
      required: false
      example: https://open.larksuite.com/open-apis/bot/v2/hook/xxx
    
    LARK_APP_ID:
      description: Lark application ID
      required: false
      example: cli_a4d3c2b1a0f9g8h7
    
    LARK_APP_SECRET:
      description: Lark application secret
      required: false
      sensitive: true
    
    LARK_VERIFICATION_TOKEN:
      description: Lark verification token for webhooks
      required: false
      sensitive: true
  
  # Google Cloud Platform
  gcp:
    GCP_STAGING_SA_KEY:
      description: Service account key for GCP authentication
      required: true
      sensitive: true
      format: json
    
    GCP_PROJECT_ID:
      description: GCP project ID
      required: true
      example: netra-staging-12345
    
    TF_STATE_BUCKET:
      description: GCS bucket for Terraform state
      required: true
      example: netra-terraform-state
  
  # Database
  database:
    DATABASE_URL:
      description: PostgreSQL connection string
      required: true
      sensitive: true
      example: postgresql://user:pass@host:5432/dbname
    
    CLICKHOUSE_URL:
      description: ClickHouse connection string
      required: false
      sensitive: true
      example: clickhouse://user:pass@host:9000/default
    
    REDIS_URL:
      description: Redis connection string
      required: false
      sensitive: true
      example: redis://user:pass@host:6379/0
  
  # AI/LLM Services
  llm:
    ANTHROPIC_API_KEY:
      description: Anthropic Claude API key
      required: false
      sensitive: true
    
    OPENAI_API_KEY:
      description: OpenAI API key
      required: false
      sensitive: true
  
  # GitHub
  github:
    GITHUB_TOKEN:
      description: GitHub personal access token with workflow permissions
      required: true
      sensitive: true
      permissions:
        - repo
        - workflow
        - write:packages
        - read:org
    
    GITHUB_WEBHOOK_SECRET:
      description: Secret for validating GitHub webhooks
      required: false
      sensitive: true

environment_secrets:
  staging:
    STAGING_DOMAIN:
      description: Base domain for staging environments
      required: false
      example: staging.netra.dev
    
    STAGING_SSL_CERT:
      description: SSL certificate for staging
      required: false
      sensitive: true
  
  production:
    PROD_DOMAIN:
      description: Production domain
      required: true
      example: app.netrasystems.ai
    
    PROD_SSL_CERT:
      description: SSL certificate for production
      required: true
      sensitive: true
    
    PROD_DATABASE_URL:
      description: Production database connection
      required: true
      sensitive: true

organization_secrets:
  # Secrets that should be set at organization level
  SONAR_TOKEN:
    description: SonarCloud token for code quality scanning
    required: false
    sensitive: true
  
  SNYK_TOKEN:
    description: Snyk token for security scanning
    required: false
    sensitive: true
  
  DATADOG_API_KEY:
    description: Datadog API key for monitoring
    required: false
    sensitive: true