# Minimal Resource Docker Compose Override for Development
# Use this when Docker Desktop is crashing due to resource exhaustion
# 
# Usage: docker-compose -f docker-compose.yml -f docker-compose.dev-minimal.yml --profile dev up -d

version: '3.8'

services:
  # Reduce PostgreSQL resources significantly
  dev-postgres:
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.25'
        reservations:
          memory: 128M

  # Reduce Redis resources
  dev-redis:
    deploy:
      resources:
        limits:
          memory: 128M
          cpus: '0.125'
        reservations:
          memory: 64M

  # Reduce ClickHouse resources significantly or disable
  dev-clickhouse:
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.25'
        reservations:
          memory: 256M

  # Reduce Auth Service resources
  dev-auth:
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.25'
        reservations:
          memory: 128M

  # Reduce Backend resources significantly
  dev-backend:
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M

  # Reduce Frontend resources significantly
  dev-frontend:
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M

# Total Resources with this override:
# Memory: ~2.2GB (down from 4.25GB)
# CPU: ~1.625 cores (down from 3.75 cores)