# Alpine-based Test Environment with Fresh Builds
# Optimized for isolation and minimal resource usage
version: '3.8'

services:
  # ============================================
  # ALPINE TEST INFRASTRUCTURE
  # ============================================
  
  alpine-test-postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: netra_test
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --data-checksums"
    ports:
      - "${ALPINE_TEST_POSTGRES_PORT:-5435}:5432"
    volumes:
      # Use tmpfs for ultra-fast ephemeral storage
      - type: tmpfs
        target: /var/lib/postgresql/data
        tmpfs:
          size: 512M
    command: |
      postgres
        -c shared_buffers=128MB
        -c max_connections=100
        -c fsync=off
        -c synchronous_commit=off
        -c full_page_writes=off
        -c checkpoint_segments=32
        -c checkpoint_completion_target=0.9
        -c wal_buffers=16MB
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test"]
      interval: 2s
      timeout: 1s
      retries: 10
      start_period: 5s
    networks:
      - default
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.25'

  alpine-test-redis:
    image: redis:7-alpine
    command: |
      redis-server
        --appendonly no
        --save ""
        --maxmemory 128mb
        --maxmemory-policy allkeys-lru
        --tcp-keepalive 60
    ports:
      - "${ALPINE_TEST_REDIS_PORT:-6382}:6379"
    volumes:
      - type: tmpfs
        target: /data
        tmpfs:
          size: 128M
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 2s
      timeout: 1s
      retries: 5
    networks:
      - default
    deploy:
      resources:
        limits:
          memory: 128M
          cpus: '0.1'

  alpine-test-clickhouse:
    image: clickhouse/clickhouse-server:23-alpine
    environment:
      CLICKHOUSE_DB: test_analytics
      CLICKHOUSE_USER: test
      CLICKHOUSE_PASSWORD: test
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
      CLICKHOUSE_LOG_LEVEL: error
    ports:
      - "${ALPINE_TEST_CLICKHOUSE_HTTP:-8126}:8123"
      - "${ALPINE_TEST_CLICKHOUSE_TCP:-9003}:9000"
    volumes:
      - type: tmpfs
        target: /var/lib/clickhouse
        tmpfs:
          size: 256M
    healthcheck:
      test: ["CMD", "wget", "-q", "-O-", "http://localhost:8123/ping"]
      interval: 3s
      timeout: 2s
      retries: 10
    networks:
      - default
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.2'

  # ============================================
  # ALPINE APPLICATION SERVICES
  # ============================================

  alpine-test-backend:
    image: netra-alpine-test-backend:latest
    build:
      context: .
      dockerfile: docker/backend.alpine.Dockerfile
      args:
        BUILD_ENV: test
      cache_from:
        - python:3.11-alpine3.19
    environment:
      ENVIRONMENT: testing
      LOG_LEVEL: ERROR
      POSTGRES_HOST: alpine-test-postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: netra_test
      REDIS_HOST: alpine-test-redis
      REDIS_PORT: 6379
      CLICKHOUSE_HOST: alpine-test-clickhouse
      CLICKHOUSE_PORT: 9000
      AUTH_SERVICE_URL: http://alpine-test-auth:8081
      TEST_MODE: "true"
      WORKERS: 2
    ports:
      - "${ALPINE_TEST_BACKEND_PORT:-8002}:8000"
    depends_on:
      alpine-test-postgres:
        condition: service_healthy
      alpine-test-redis:
        condition: service_healthy
      alpine-test-clickhouse:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 3s
      timeout: 2s
      retries: 10
      start_period: 15s
    networks:
      - default
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'

  alpine-test-auth:
    image: netra-alpine-test-auth:latest
    build:
      context: .
      dockerfile: docker/auth.alpine.Dockerfile
      args:
        BUILD_ENV: test
      cache_from:
        - python:3.11-alpine3.19
    environment:
      ENVIRONMENT: testing
      LOG_LEVEL: ERROR
      POSTGRES_HOST: alpine-test-postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: netra_test
      REDIS_HOST: alpine-test-redis
      REDIS_PORT: 6379
      TEST_MODE: "true"
      JWT_SECRET_KEY: test_jwt_secret_key
      SERVICE_SECRET: test_service_secret
    ports:
      - "${ALPINE_TEST_AUTH_PORT:-8083}:8081"
    depends_on:
      alpine-test-postgres:
        condition: service_healthy
      alpine-test-redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/health"]
      interval: 3s
      timeout: 2s
      retries: 10
      start_period: 15s
    networks:
      - default
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.25'

  alpine-test-frontend:
    image: netra-alpine-test-frontend:latest
    build:
      context: .
      dockerfile: docker/frontend.alpine.Dockerfile
      args:
        BUILD_ENV: test
        NEXT_PUBLIC_API_URL: http://alpine-test-backend:8000
        NEXT_PUBLIC_AUTH_URL: http://alpine-test-auth:8081
        NEXT_PUBLIC_WS_URL: ws://alpine-test-backend:8000
        NEXT_PUBLIC_ENVIRONMENT: test
      cache_from:
        - node:20-alpine3.19
    environment:
      NODE_ENV: test
      PORT: 3000
    ports:
      - "${ALPINE_TEST_FRONTEND_PORT:-3002}:3000"
    depends_on:
      alpine-test-backend:
        condition: service_healthy
      alpine-test-auth:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 30s
    networks:
      - default
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.3'

networks:
  default:
    driver: bridge
    # Network name will be prefixed with project name automatically
    driver_opts:
      com.docker.network.driver.mtu: 1500

# No persistent volumes - everything is ephemeral for test isolation