# Minimal Resource Docker Compose Override for Development
# Use this when Docker Desktop is crashing due to resource exhaustion
# 
# Usage: docker-compose -f docker-compose.yml -f docker-compose.dev-minimal.yml --profile dev up -d

version: '3.8'

services:
  # Reduce PostgreSQL resources significantly
  dev-postgres:
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.25'
        reservations:
          memory: 128M

  # Reduce Redis resources
  dev-redis:
    deploy:
      resources:
        limits:
          memory: 128M
          cpus: '0.125'
        reservations:
          memory: 64M

  # Reduce ClickHouse resources significantly or disable
  dev-clickhouse:
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.25'
        reservations:
          memory: 256M

  # Reduce Auth Service resources
  dev-auth:
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.25'
        reservations:
          memory: 128M

  # Increased Backend resources for stability
  dev-backend:
    deploy:
      resources:
        limits:
          memory: 3G
          cpus: '1.5'
        reservations:
          memory: 1G

  # Increased Frontend resources for development
  dev-frontend:
    deploy:
      resources:
        limits:
          memory: 3G
          cpus: '1.5'
        reservations:
          memory: 1G

# Total Resources with this override:
# Memory: ~7.9GB (backend+frontend: 6GB, others: 1.9GB)
# CPU: ~3.625 cores (backend+frontend: 3 cores, others: 0.625 cores)