services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: netra-postgres
    profiles: ["db", "backend", "full"]
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-netra}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-netra123}
      POSTGRES_DB: ${POSTGRES_DB:-netra_dev}
      POSTGRES_HOST_AUTH_METHOD: trust
      # Enable proper shutdown handling
      POSTGRES_INITDB_ARGS: "--data-checksums"
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init_db.sql:/docker-entrypoint-initdb.d/01-init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-netra} && psql -U ${POSTGRES_USER:-netra} -d netra_dev -c 'SELECT 1' > /dev/null 2>&1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    # Graceful shutdown configuration
    stop_signal: SIGTERM
    stop_grace_period: 30s
    networks:
      - netra-network

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: netra-redis
    profiles: ["cache", "backend", "full"]
    command: redis-server --appendonly yes
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - netra-network

  # ClickHouse Analytics (Required for real analytics)
  clickhouse:
    image: clickhouse/clickhouse-server:23-alpine
    container_name: netra-clickhouse
    profiles: ["backend", "analytics", "full"]
    environment:
      CLICKHOUSE_DB: ${CLICKHOUSE_DB:-netra_analytics}
      CLICKHOUSE_USER: ${CLICKHOUSE_USER:-netra}
      CLICKHOUSE_PASSWORD: ${CLICKHOUSE_PASSWORD:-netra123}
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
    ports:
      - "${CLICKHOUSE_HTTP_PORT:-8123}:8123"
      - "${CLICKHOUSE_TCP_PORT:-9000}:9000"
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - ./scripts/init_clickhouse.sql:/docker-entrypoint-initdb.d/01-init.sql:ro
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://127.0.0.1:8123/ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - netra-network

  # Backend Service (Main Netra Application)
  backend:
    build:
      context: .
      dockerfile: ./docker/backend.development.Dockerfile
    container_name: netra-backend
    profiles: ["netra", "backend", "full"]
    env_file:
      - .env.development
    environment:
      # Database
      DATABASE_URL: postgresql://${POSTGRES_USER:-netra}:${POSTGRES_PASSWORD:-netra123}@postgres:5432/${POSTGRES_DB:-netra_dev}
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: ${POSTGRES_USER:-netra}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-netra123}
      POSTGRES_DB: ${POSTGRES_DB:-netra_dev}
      
      # Redis
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_URL: redis://redis:6379/0
      REDIS_STAGING_HOST: ${REDIS_STAGING_HOST:-redis-staging.internal}
      REDIS_PRODUCTION_HOST: ${REDIS_PRODUCTION_HOST:-redis-production.internal}
      
      # ClickHouse
      CLICKHOUSE_HOST: clickhouse
      CLICKHOUSE_PORT: 8123
      CLICKHOUSE_USER: ${CLICKHOUSE_USER:-netra}
      CLICKHOUSE_PASSWORD: ${CLICKHOUSE_PASSWORD:-netra123}
      
      # Auth Service
      AUTH_SERVICE_URL: http://auth:8081
      
      # Server Config
      PORT: 8000
      HOST: 0.0.0.0
      ENVIRONMENT: ${ENVIRONMENT:-development}
      
      # Security
      SECRET_KEY: ${SECRET_KEY:-dev-secret-key-change-in-production-must-be-at-least-32-chars}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY:-dev-secret-key-change-in-production-must-be-at-least-32-chars}
      FERNET_KEY: ${FERNET_KEY:-dev-fernet-key-change-in-production}
      SERVICE_SECRET: ${SERVICE_SECRET}
      
      # API Keys (from .env.development)
      ANTHROPIC_API_KEY: ${ANTHROPIC_API_KEY}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      NETRA_API_KEY: ${NETRA_API_KEY}
      GEMINI_API_KEY: ${GEMINI_API_KEY}
      
      # Grafana Admin Password
      GRAFANA_ADMIN_PASSWORD: ${GRAFANA_ADMIN_PASSWORD}
      
      # Frontend URL
      FRONTEND_URL: http://localhost:3000
      # CORS_ORIGINS removed to use comprehensive list from shared/cors_config.py
      
      # Development Auth Bypass
      ALLOW_DEV_AUTH_BYPASS: true
      WEBSOCKET_AUTH_BYPASS: true
    ports:
      - "${BACKEND_PORT:-8000}:8000"
    volumes:
      - ./netra_backend:/app/netra_backend
      - ./shared:/app/shared
      - ./SPEC:/app/SPEC
      - ./scripts:/app/scripts
      - ./logs:/app/logs
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      clickhouse:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - netra-network
    command: >
      sh -c "
        echo 'Waiting for database...' &&
        python scripts/wait_for_db.py &&
        echo 'Running migrations...' &&
        alembic -c netra_backend/alembic.ini upgrade head &&
        echo 'Starting backend...' &&
        uvicorn netra_backend.app.main:app --host 0.0.0.0 --port 8000 --reload --reload-dir /app/netra_backend --reload-dir /app/shared --reload-include '*.py'
      "

  # Auth Service
  auth:
    build:
      context: .
      dockerfile: ./docker/auth.development.Dockerfile
    container_name: netra-auth
    profiles: ["auth", "backend", "full"]
    env_file:
      - .env.development
    environment:
      # Database
      DATABASE_URL: postgresql://${POSTGRES_USER:-netra}:${POSTGRES_PASSWORD:-netra123}@postgres:5432/${POSTGRES_DB:-netra_dev}
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      
      # Redis
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_URL: redis://redis:6379/1
      REDIS_STAGING_HOST: ${REDIS_STAGING_HOST:-redis-staging.internal}
      REDIS_PRODUCTION_HOST: ${REDIS_PRODUCTION_HOST:-redis-production.internal}
      
      # Server Config
      PORT: 8081
      HOST: 0.0.0.0
      ENVIRONMENT: ${ENVIRONMENT:-development}
      
      # Auth Config
      JWT_SECRET_KEY: ${JWT_SECRET_KEY:-zZyIqeCZia66c1NxEgNowZFWbwMGROFg}
      JWT_ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 30
      SERVICE_SECRET: xNp9hKjT5mQ8w2fE7vR4yU3iO6aS1gL9cB0zZ8tN6wX2eR4vY7uI0pQ3s9dF5gH8
      SERVICE_ID: auth
      
      # OAuth Configuration
      GOOGLE_OAUTH_CLIENT_ID_DEVELOPMENT: ${GOOGLE_OAUTH_CLIENT_ID_DEVELOPMENT}
      GOOGLE_OAUTH_CLIENT_SECRET_DEVELOPMENT: ${GOOGLE_OAUTH_CLIENT_SECRET_DEVELOPMENT}
      GOOGLE_OAUTH_CLIENT_ID_STAGING: ${GOOGLE_OAUTH_CLIENT_ID_STAGING}
      GOOGLE_OAUTH_CLIENT_SECRET_STAGING: ${GOOGLE_OAUTH_CLIENT_SECRET_STAGING}
      
      # GitHub OAuth Configuration
      GITHUB_OAUTH_CLIENT_ID_DEVELOPMENT: ${GITHUB_OAUTH_CLIENT_ID_DEVELOPMENT}
      GITHUB_OAUTH_CLIENT_SECRET_DEVELOPMENT: ${GITHUB_OAUTH_CLIENT_SECRET_DEVELOPMENT}
      
      # Legacy OAuth Support
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      OAUTH_CLIENT_ID: ${OAUTH_CLIENT_ID}
      OAUTH_CLIENT_SECRET: ${OAUTH_CLIENT_SECRET}
      OAUTH_REDIRECT_URI: ${OAUTH_REDIRECT_URI}
    ports:
      - "${AUTH_PORT:-8081}:8081"
    volumes:
      - ./auth_service:/app/auth_service
      - ./shared:/app/shared
      - ./logs:/app/logs
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - netra-network
    command: >
      sh -c "
        echo 'Starting auth service...' &&
        uvicorn auth_service.main:app --host 0.0.0.0 --port 8081 --reload --reload-dir /app/auth_service --reload-dir /app/shared --reload-include '*.py'
      "

  # Frontend Service
  frontend:
    build:
      context: .
      dockerfile: ./docker/frontend.development.Dockerfile
      args:
        BUILD_MODE: development
    container_name: netra-frontend
    profiles: ["frontend", "full"]
    env_file:
      - .env.development
    environment:
      # API URLs (External - for browser connections from host)
      NEXT_PUBLIC_API_URL: http://localhost:8000
      NEXT_PUBLIC_AUTH_URL: http://localhost:8081
      NEXT_PUBLIC_WS_URL: ws://localhost:8000
      NEXT_PUBLIC_WEBSOCKET_URL: ws://localhost:8000/ws
      
      # Internal API URLs (for SSR and Docker networking)
      API_URL: http://backend:8000
      AUTH_URL: http://auth:8081
      WS_URL: ws://backend:8000
      
      # Next.js Config
      NODE_ENV: development
      NEXT_TELEMETRY_DISABLED: 1
      
      # Feature Flags
      NEXT_PUBLIC_ENVIRONMENT: ${ENVIRONMENT:-development}
    ports:
      - "${FRONTEND_PORT:-3000}:3000"
    volumes:
      - ./frontend/src:/app/src:ro
      - ./frontend/public:/app/public:ro
      - ./frontend/next.config.ts:/app/next.config.ts:ro
      - ./frontend/next.config.turbopack.ts:/app/next.config.turbopack.ts:ro
      - ./frontend/tsconfig.json:/app/tsconfig.json:ro
      - ./frontend/tailwind.config.ts:/app/tailwind.config.ts:ro
      - ./frontend/postcss.config.mjs:/app/postcss.config.mjs:ro
      # Exclude node_modules from volume mount to use container's installed packages
      - /app/node_modules
      - /app/.next
    depends_on:
      - backend
      - auth
    networks:
      - netra-network
    command: npm run dev

networks:
  netra-network:
    driver: bridge
    name: netra-network

volumes:
  postgres_data:
    name: netra-postgres-data
  redis_data:
    name: netra-redis-data
  clickhouse_data:
    name: netra-clickhouse-data