# Docker Compose Override for Local Development
# 
# IMPORTANT: This file provides bind mounts for active development where you need
# real-time file synchronization. Only use this when necessary as bind mounts can
# cause Docker Desktop crashes on Windows/macOS.
#
# To use bind mounts for development:
# - docker-compose --profile dev up
#
# To use only named volumes (more stable):
# - mv docker-compose.override.yml docker-compose.override.yml.disabled
# - docker-compose --profile dev up
#
# WARNING: Bind mounts can cause:
# - High CPU/memory usage
# - Docker Desktop crashes
# - Slow file operations
# - File permission issues

version: '3.8'

services:
  # Dev Auth Service - Bind mount override
  dev-auth:
    volumes:
      # Bind mount for live code editing
      # Use delegated for better performance on macOS
      - ./auth_service:/app/auth_service:delegated
      - ./shared:/app/shared:delegated
      - ./logs/auth:/app/logs:delegated
      # Exclude Python cache from bind mount
      - /app/auth_service/__pycache__
      - /app/shared/__pycache__

  # Dev Analytics Service - Bind mount override
  dev-analytics:
    volumes:
      - ./analytics_service:/app/analytics_service:delegated
      - ./shared:/app/shared:delegated
      - ./logs/analytics:/app/logs:delegated
      # Exclude Python cache
      - /app/analytics_service/__pycache__
      - /app/shared/__pycache__

  # Dev Backend Service - Bind mount override
  dev-backend:
    volumes:
      - ./netra_backend:/app/netra_backend:delegated
      - ./shared:/app/shared:delegated
      - ./SPEC:/app/SPEC:delegated
      - ./scripts:/app/scripts:delegated
      - ./logs/backend:/app/logs:delegated
      # Exclude Python cache
      - /app/netra_backend/__pycache__
      - /app/shared/__pycache__
      - /app/scripts/__pycache__

  # Dev Frontend Service - Bind mount override
  dev-frontend:
    volumes:
      # Selective bind mounts for frontend development
      # Mount only source directories, not node_modules
      - ./frontend/src:/app/src:delegated
      - ./frontend/public:/app/public:delegated
      - ./frontend/app:/app/app:delegated
      - ./frontend/auth:/app/auth:delegated
      - ./frontend/components:/app/components:delegated
      - ./frontend/hooks:/app/hooks:delegated
      - ./frontend/lib:/app/lib:delegated
      - ./frontend/services:/app/services:delegated
      - ./frontend/store:/app/store:delegated
      - ./frontend/styles:/app/styles:delegated
      - ./frontend/types:/app/types:delegated
      - ./frontend/utils:/app/utils:delegated
      - ./frontend/providers:/app/providers:delegated
      - ./frontend/scripts:/app/scripts:delegated
      # Configuration files
      - ./frontend/next.config.ts:/app/next.config.ts:delegated
      - ./frontend/next.config.turbopack.ts:/app/next.config.turbopack.ts:delegated
      - ./frontend/tsconfig.json:/app/tsconfig.json:delegated
      - ./frontend/tailwind.config.ts:/app/tailwind.config.ts:delegated
      - ./frontend/postcss.config.mjs:/app/postcss.config.mjs:delegated
      - ./frontend/package.json:/app/package.json:delegated
      - ./frontend/package-lock.json:/app/package-lock.json:delegated
      # CRITICAL: Keep node_modules and .next in named volumes
      - dev_frontend_node_modules:/app/node_modules
      - dev_frontend_next:/app/.next
      - dev_frontend_cache:/app/.cache

# Performance optimization tips:
# 1. Use :delegated on macOS for better write performance
# 2. Use :cached for read-heavy directories
# 3. Exclude build artifacts and dependencies from bind mounts
# 4. Consider using mutagen or docker-sync for better performance
# 5. Regularly prune unused volumes: docker volume prune