# Development Override Configuration with Bind Mounts
# 
# This file adds bind mounts for active development with hot-reloading.
# WARNING: This may cause Docker Desktop stability issues on Windows/macOS.
# Use only when actively developing.
#
# To use: docker-compose -f docker-compose.yml -f docker-compose.dev.override.yml --profile dev up

version: '3.8'

services:
  # Dev Backend Service - Add bind mounts for hot-reloading
  dev-backend:
    volumes:
      # Override to add bind mounts for development
      - backend_data:/app/data
      - ./netra_backend:/app/netra_backend:cached
      - ./shared:/app/shared:cached
      - ./scripts:/app/scripts:cached
      - ./SPEC:/app/SPEC:cached
      - ./test_framework:/app/test_framework:cached
    environment:
      # Enable auto-reload for development
      RELOAD: "true"
      PYTHONDONTWRITEBYTECODE: 1
      PYTHONUNBUFFERED: 1

  # Dev Auth Service - Add bind mounts for hot-reloading
  dev-auth:
    volumes:
      # Override to add bind mounts for development
      - backend_data:/app/data
      - ./auth_service:/app/auth_service:cached
      - ./shared:/app/shared:cached
    environment:
      # Enable auto-reload for development
      RELOAD: "true"
      PYTHONDONTWRITEBYTECODE: 1
      PYTHONUNBUFFERED: 1

  # Dev Frontend Service - Add bind mounts for hot-reloading
  dev-frontend:
    volumes:
      # Bind mount source code for hot-reloading
      - ./frontend:/app:cached
      # Use named volume for node_modules to avoid sync issues
      - frontend_node_modules:/app/node_modules
      - frontend_next:/app/.next
    environment:
      # Enable Next.js dev mode with hot-reloading
      NODE_ENV: development
      NEXT_TELEMETRY_DISABLED: 1

# Additional volumes for development
volumes:
  # Frontend development volumes
  frontend_node_modules:
    name: netra-dev-frontend-node-modules
  frontend_next:
    name: netra-dev-frontend-next