version: '3.8'

services:
  auth-service:
    build:
      context: .
      dockerfile: Dockerfile.auth
    container_name: netra-auth-service
    ports:
      - "8081:8080"
    environment:
      - ENVIRONMENT=development
      - SERVICE_NAME=auth-service
      - PORT=8080
      - LOG_LEVEL=INFO
      - JWT_SECRET=your-development-jwt-secret-change-in-production
      - REDIS_URL=redis://redis:6379/0
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/auth_db
      - CORS_ORIGINS=http://localhost:3000,http://localhost:8000
    depends_on:
      - redis
      - postgres
    networks:
      - netra-network
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: netra-auth-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - netra-network
    restart: unless-stopped

  postgres:
    image: postgres:15-alpine
    container_name: netra-auth-postgres
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=auth_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - netra-network
    restart: unless-stopped

networks:
  netra-network:
    driver: bridge

volumes:
  redis-data:
  postgres-data: