'''Add Assistant, Thread, Message, Run, and Step models

Revision ID: cd076abbe30a
Revises: 9138f063f453
Create Date: 2025-08-08 19:07:08.011256

'''
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd076abbe30a'
down_revision = '9138f063f453'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assistants',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('object', sa.String(), nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('instructions', sa.String(), nullable=True),
    sa.Column('tools', sa.JSON(), nullable=False),
    sa.Column('file_ids', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('metadata_', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('threads',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('object', sa.String(), nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.Column('metadata_', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('runs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('object', sa.String(), nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.Column('thread_id', sa.String(), nullable=False),
    sa.Column('assistant_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('required_action', sa.JSON(), nullable=True),
    sa.Column('last_error', sa.JSON(), nullable=True),
    sa.Column('expires_at', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.Integer(), nullable=True),
    sa.Column('cancelled_at', sa.Integer(), nullable=True),
    sa.Column('failed_at', sa.Integer(), nullable=True),
    sa.Column('completed_at', sa.Integer(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('instructions', sa.String(), nullable=True),
    sa.Column('tools', sa.JSON(), nullable=False),
    sa.Column('file_ids', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('metadata_', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['assistant_id'], ['assistants.id'], ),
    sa.ForeignKeyConstraint(['thread_id'], ['threads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('messages',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('object', sa.String(), nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.Column('thread_id', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('assistant_id', sa.String(), nullable=True),
    sa.Column('run_id', sa.String(), nullable=True),
    sa.Column('file_ids', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('metadata_', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['assistant_id'], ['assistants.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.ForeignKeyConstraint(['thread_id'], ['threads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('steps',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('object', sa.String(), nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('assistant_id', sa.String(), nullable=False),
    sa.Column('thread_id', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('step_details', sa.JSON(), nullable=False),
    sa.Column('last_error', sa.JSON(), nullable=True),
    sa.Column('expired_at', sa.Integer(), nullable=True),
    sa.Column('cancelled_at', sa.Integer(), nullable=True),
    sa.Column('failed_at', sa.Integer(), nullable=True),
    sa.Column('completed_at', sa.Integer(), nullable=True),
    sa.Column('metadata_', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['assistant_id'], ['assistants.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.ForeignKeyConstraint(['thread_id'], ['threads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('steps')
    op.drop_table('messages')
    op.drop_table('runs')
    op.drop_table('threads')
    op.drop_table('assistants')
    # ### end Alembic commands ###
