generation_settings:
  num_traces: 5
  trace_distribution:
    failed_request: 0.09000000000000001
    multi_turn_tool_use: 0.1
    rag_pipeline: 0.27
    simple_chat: 0.36000000000000004
    tool_use: 0.18000000000000002
overrides: {}
realism:
  applications:
  - app_name: customer-support-chatbot
    services:
    - intent-classifier
    - chat-responder
    - history-summarizer
  - app_name: marketing-copy-generator
    services:
    - headline-generator
    - body-text-creator
    - seo-analyzer
  - app_name: internal-doc-search
    services:
    - query-parser
    - retrieval-engine
    - answer-generator
  models:
  - family: gpt-4
    name: gpt-4o
    pricing:
    - 5.0
    - 15.0
    provider: openai
    version_id: gpt-4o-2024-08-06
  - family: claude-3
    name: claude-3-opus
    pricing:
    - 15.0
    - 75.0
    provider: anthropic
    version_id: claude-3-opus-20240229
  - family: gemini-2.0
    name: gemini-2.0-flash
    pricing:
    - 0.35
    - 0.7
    provider: google
    version_id: null
  - family: llama-3.1
    name: llama-3.1-70b-instruct
    pricing:
    - 0.5
    - 0.5
    provider: vllm
    version_id: null
