generation_settings:
  num_traces: 10000
  trace_distribution:
    simple_chat: 0.25
    rag_pipeline: 0.25
    tool_use: 0.25
    multi_turn_tool_use: 0.20
    failed_request: 0.05
overrides: {}
realism:
  applications:
  - app_name: customer-support-chatbot
    services:
    - intent-classifier
    - chat-responder
    - history-summarizer
  - app_name: marketing-copy-generator
    services:
    - headline-generator
    - body-text-creator
    - seo-analyzer
  - app_name: internal-doc-search
    services:
    - query-parser
    - retrieval-engine
    - answer-generator
  - app_name: financial-forecasting-agent
    services:
    - data-retrieval-tool
    - time-series-analyzer
    - report-generator
  models:
  - family: gpt-4
    name: gpt-4o
    pricing:
    - 5.0
    - 15.0
    provider: openai
    version_id: gpt-4o-2024-08-06
  - family: gpt-4
    name: gpt-4-turbo
    pricing:
    - 10.0
    - 30.0
    provider: openai
    version_id: gpt-4-turbo-2024-04-09
  - family: claude-3
    name: claude-3-opus
    pricing:
    - 15.0
    - 75.0
    provider: anthropic
    version_id: claude-3-opus-20240229
  - family: claude-3
    name: claude-3-sonnet
    pricing:
    - 3.0
    - 15.0
    provider: anthropic
    version_id: claude-3-sonnet-20240229
  - family: gemini-1.5
    name: gemini-1.5-pro
    pricing:
    - 3.5
    - 10.5
    provider: google
    version_id: null
  - family: llama-3.1
    name: llama-3.1-70b-instruct
    pricing:
    - 0.59
    - 0.79
    provider: vllm
    version_id: null
  - family: llama-3.1
    name: llama-3.1-8b-instruct
    pricing:
    - 0.2
    - 0.2
    provider: vllm
    version_id: null