# Auto-generated Development Environment Configuration
# Generated by Terraform - DO NOT EDIT MANUALLY
# Run 'terraform apply' in terraform-dev-postgres/ to regenerate

ENVIRONMENT=development

# PostgreSQL Database Configuration
DATABASE_URL=postgresql+asyncpg://${postgres_user}:${postgres_password}@${postgres_host}:${postgres_port}/${postgres_db}
POSTGRES_HOST=${postgres_host}
POSTGRES_PORT=${postgres_port}
POSTGRES_DB=${postgres_db}
POSTGRES_USER=${postgres_user}
POSTGRES_PASSWORD=${postgres_password}

# Application Database User
APP_DB_USER=${app_user}
APP_DB_PASSWORD=${app_password}

# Redis Configuration
REDIS_URL=redis://${redis_host}:${redis_port}/0
REDIS_HOST=${redis_host}
REDIS_PORT=${redis_port}

# ClickHouse Configuration
CLICKHOUSE_URL=clickhouse://${clickhouse_user}:${clickhouse_password}@${clickhouse_host}:${clickhouse_native_port}/${clickhouse_db}
CLICKHOUSE_HOST=${clickhouse_host}
CLICKHOUSE_HTTP_PORT=${clickhouse_http_port}
CLICKHOUSE_NATIVE_PORT=${clickhouse_native_port}
CLICKHOUSE_DB=${clickhouse_db}
CLICKHOUSE_USER=${clickhouse_user}
CLICKHOUSE_PASSWORD=${clickhouse_password}

# Security Keys
SECRET_KEY=${secret_key}
JWT_SECRET_KEY=${jwt_secret}

# Frontend Configuration
FRONTEND_URL=http://localhost:3000
API_URL=http://localhost:8000
NEXT_PUBLIC_API_URL=http://localhost:8000
NEXT_PUBLIC_WS_URL=ws://localhost:8000

# OAuth Configuration (Development)
GOOGLE_OAUTH_CLIENT_ID_DEV=your-dev-client-id-here
GOOGLE_OAUTH_CLIENT_SECRET_DEV=your-dev-client-secret-here

# Development Features
ALLOW_DEV_LOGIN=true
ALLOW_MOCK_AUTH=true
DEBUG=true
RELOAD=true

# Logging
LOG_LEVEL=DEBUG
LOG_FORMAT=detailed

# Performance Settings
MAX_CONNECTIONS=100
POOL_SIZE=20
POOL_OVERFLOW=10
POOL_TIMEOUT=30

# WebSocket Settings
WS_PING_INTERVAL=30
WS_PING_TIMEOUT=10
WS_MAX_CONNECTIONS=100

# Feature Flags
ENABLE_METRICS=true
ENABLE_TRACING=false
ENABLE_PROFILING=false

# Docker Network (for inter-container communication)
DOCKER_NETWORK=netra-dev-network

# Health Check Settings
HEALTH_CHECK_INTERVAL=30
HEALTH_CHECK_TIMEOUT=5

# Backup Settings (disabled for dev)
ENABLE_BACKUPS=false

# Rate Limiting (relaxed for development)
RATE_LIMIT_ENABLED=false
RATE_LIMIT_REQUESTS=1000
RATE_LIMIT_WINDOW=60

# Cache Settings
CACHE_TTL=300
CACHE_MAX_SIZE=1000

# Model Settings (if needed)
OPENAI_API_KEY=
ANTHROPIC_API_KEY=
GEMINI_API_KEY=

# Monitoring (optional)
SENTRY_DSN=
DATADOG_API_KEY=

# File Upload Settings
MAX_UPLOAD_SIZE=10485760
UPLOAD_PATH=./uploads

# Session Settings
SESSION_LIFETIME=86400
SESSION_SECURE=false

# CORS Settings
CORS_ORIGINS=http://localhost:3000,http://localhost:8000
CORS_CREDENTIALS=true

# Testing
TEST_MODE=false
TEST_DATABASE_URL=postgresql+asyncpg://${postgres_user}:${postgres_password}@${postgres_host}:${postgres_port}/netra_test