images:
- gcr.io/netra-staging/netra-backend-staging:latest
steps:
- args:
  - build
  - -t
  - gcr.io/netra-staging/netra-backend-staging:latest
  - -f
  - deployment/docker/backend.gcp.Dockerfile
  - .
  name: gcr.io/cloud-builders/docker
