steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/cryptic-net-466001-n0/github-runners/runner:latest', '.']
  
  # Push the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/cryptic-net-466001-n0/github-runners/runner:latest']

images:
  - 'us-central1-docker.pkg.dev/cryptic-net-466001-n0/github-runners/runner:latest'