"""Add hashed_password to user

Revision ID: cfb7e3adde23
Revises: a12de78b4ee4
Create Date: 2025-08-09 11:33:22.925492

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfb7e3adde23'
down_revision: Union[str, Sequence[str], None] = 'a12de78b4ee4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userbase', sa.Column('hashed_password', sa.String(), nullable=True))
    op.drop_index(op.f('ix_users_email'), table_name='userbase')
    op.drop_index(op.f('ix_users_full_name'), table_name='userbase')
    op.create_index(op.f('ix_userbase_email'), 'userbase', ['email'], unique=True)
    op.create_index(op.f('ix_userbase_full_name'), 'userbase', ['full_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_userbase_full_name'), table_name='userbase')
    op.drop_index(op.f('ix_userbase_email'), table_name='userbase')
    op.create_index(op.f('ix_users_full_name'), 'userbase', ['full_name'], unique=False)
    op.create_index(op.f('ix_users_email'), 'userbase', ['email'], unique=True)
    op.drop_column('userbase', 'hashed_password')
    # ### end Alembic commands ###
