#!/bin/bash

# GitHub Issue #885 Manual Operations Script
# Created: September 15, 2025
# Purpose: Add labels and post comprehensive status update comment

echo "=== GitHub Issue #885 Manual Operations ==="
echo ""

# Add labels to issue #885
echo "1. Adding labels to issue #885..."
gh issue edit 885 --add-label "actively-being-worked-on,agent-session-2025-09-15-185627"
if [ $? -eq 0 ]; then
    echo "✅ Labels added successfully"
else
    echo "❌ Failed to add labels - may require manual addition via GitHub web interface"
    echo "Required labels: actively-being-worked-on, agent-session-2025-09-15-185627"
fi

echo ""

# Post comprehensive status update comment
echo "2. Posting comprehensive status update comment..."
if [ -f "issue_885_comprehensive_status_update_comment.md" ]; then
    # Extract comment content (exclude manual operations section)
    sed '/^## Manual GitHub Actions Required/,$d' issue_885_comprehensive_status_update_comment.md > temp_comment.md

    gh issue comment 885 --body-file temp_comment.md
    if [ $? -eq 0 ]; then
        echo "✅ Comment posted successfully"
        # Get the comment ID (this would need to be retrieved from GitHub)
        echo "📝 Comment ID: [Will be generated by GitHub]"
    else
        echo "❌ Failed to post comment - may require manual posting via GitHub web interface"
        echo "📄 Comment content available in: issue_885_comprehensive_status_update_comment.md"
    fi

    # Clean up temporary file
    rm -f temp_comment.md
else
    echo "❌ Comment file not found: issue_885_comprehensive_status_update_comment.md"
fi

echo ""
echo "=== Manual Actions Required if Script Failed ==="
echo "1. Navigate to: https://github.com/netra-systems/netra-apex/issues/885"
echo "2. Add labels: actively-being-worked-on, agent-session-2025-09-15-185627"
echo "3. Copy content from issue_885_comprehensive_status_update_comment.md and post as comment"
echo "4. Note the comment ID for tracking purposes"
echo ""
echo "=== Documentation ==="
echo "📊 Test Results: COMPREHENSIVE_WEBSOCKET_SSOT_TEST_EXECUTION_REPORT_ISSUE_885.md"
echo "💬 Comment Content: issue_885_comprehensive_status_update_comment.md"
echo "🤖 Session: agent-session-2025-09-15-185627"