apiVersion: v1
kind: Namespace
metadata:
  name: zen-secrets
  labels:
    app.kubernetes.io/name: zen-secrets
    app.kubernetes.io/component: secret-management
    app.kubernetes.io/part-of: zen-platform
    security.policy/enforce-pod-security: "restricted"
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Namespace","metadata":{"name":"zen-secrets"}}
---
apiVersion: v1
kind: NetworkPolicy
metadata:
  name: zen-secrets-network-policy
  namespace: zen-secrets
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: zen-secrets
    - namespaceSelector:
        matchLabels:
          name: monitoring
  egress:
  - to: []
    ports:
    - protocol: TCP
      port: 443  # HTTPS
    - protocol: TCP
      port: 53   # DNS
    - protocol: UDP
      port: 53   # DNS