name: Build Release Artifacts

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

permissions:
  contents: read

jobs:
  build:
    if: ${{ secrets.COMMUNITY_CREDENTIALS != '' }}
    runs-on: ubuntu-latest
    env:
      COMMUNITY_CREDENTIALS: ${{ secrets.COMMUNITY_CREDENTIALS }}
      ZEN_TELEMETRY_SAMPLE_RATE: "1.0"
      PYTHONPATH: ${{ github.workspace }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build opentelemetry-sdk opentelemetry-exporter-gcp-trace google-cloud-trace

      - name: Clean distribution directory
        run: rm -rf dist

      - name: Embed release credentials
        run: python scripts/embed_release_credentials.py

      - name: Build distribution
        run: python -m build

      - name: Restore runtime credential loader
        if: always()
        run: git checkout -- zen/telemetry/embedded_credentials.py

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: netra-zen-dist
          path: dist/
