name: Emergency Syntax Validation
# Prevents syntax errors from breaking test infrastructure
# Part of Test Infrastructure Reliability Cluster emergency stabilization

on:
  push:
    branches: [main, develop, develop-long-lived]
    paths:
      - '**.py'
  pull_request:
    branches: [main, develop, develop-long-lived]
    paths:
      - '**.py'

jobs:
  syntax-validation:
    runs-on: ubuntu-latest
    name: 🔍 Syntax Validation (Emergency Stabilization)
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Validate Python syntax - All test directories
        run: |
          echo "🚨 EMERGENCY SYNTAX VALIDATION - Test Infrastructure Reliability"
          echo "Preventing syntax errors that break test collection and CI/CD"
          echo ""
          
          # Validate all critical test directories
          python3 scripts/validate_syntax.py tests/ || exit 1
          python3 scripts/validate_syntax.py netra_backend/tests/ || exit 1  
          python3 scripts/validate_syntax.py test_framework/ || exit 1
          python3 scripts/validate_syntax.py auth_service/ || exit 1
          
          echo ""
          echo "✅ SYNTAX VALIDATION PASSED - Test infrastructure protected"
          
      - name: Validate core application syntax
        run: |
          echo "🔍 Validating core application syntax"
          
          # Validate main application directories
          python3 scripts/validate_syntax.py netra_backend/app/ || exit 1
          python3 scripts/validate_syntax.py auth_service/auth_core/ || exit 1
          python3 scripts/validate_syntax.py shared/ || exit 1
          
          echo "✅ Core application syntax validated"
          
      - name: Report validation summary
        if: success()
        run: |
          echo ""
          echo "🎉 EMERGENCY STABILIZATION SUCCESS"
          echo "=================================="
          echo "✅ All Python files have valid syntax"
          echo "✅ Test infrastructure is protected"
          echo "✅ CI/CD pipeline reliability maintained"
          echo "✅ $500K+ ARR business value protected"